### ISSUE TITLE
Old dependencies

### ISSUE THREAD

**Issue by maasencioh** [cheminfo-js/spectra-data#5]
Hello guys, when you run npm test you have the following error:

```
> spectra-data@1.7.8 test /Users/maasencioh/Documents/cheminfo/DARMN/spectra-data
> mocha --require should --reporter mocha-better-spec-reporter --recursive

module.js:327
    throw err;
    ^

Error: Cannot find module 'ml-stat/array'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/node_modules/ml-matrix-peaks-finder/src/index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/src/PeakPicking2D.js:5:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/src/NMR2D.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/src/index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/test/main1D.js:6:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/maasencioh/Documents/cheminfo/DARMN/spectra-data/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by andcastillo** [comment]
Closed via: 9f6d500
